export const API_URI = 'https://api.postimees.ee/rest/v1';

export const CHANGE_SECTION = 'CHANGE_SECTION';

export const GET_ARTICLES_REQUEST = 'GET_ARTICLES_REQUEST';
export const GET_ARTICLES_SUCCESS = 'GET_ARTICLES_SUCCESS';
export const GET_ARTICLES_FAILED = 'GET_ARTICLES_FAILED';

export const GET_SECTIONS_REQUEST = 'GET_SECTIONS_REQUEST';
export const GET_SECTIONS_SUCCESS = 'GET_SECTIONS_SUCCESS';
export const GET_SECTIONS_FAILED = 'GET_SECTIONS_FAILED';
